apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.deploy.configMapRef.name}}
data:
{{- with .Values.configMap.data }}
    ENVIRONMENT: {{ .ENVIRONMENT | quote }}
    HOST: {{ .HOST | quote }}
    PORT:  {{ .PORT | quote }}
    REDIS_HOST: {{ .REDIS_HOST }}
    REDIS_PORT: {{ .REDIS_PORT | quote  }}
    REDIS_DB: {{ .REDIS_DB | quote }}
{{- end }}
