apiVersion: v1
kind: ConfigMap
metadata:
  name: python-env-vars
data:
{{- with .Values.configMap.data }}
    ENVIRONMENT: {{ .ENVIRONMENT }}
    HOST: {{ .HOST }}
    PORT: {{ .PORT }}
    REDIS_HOST: {{ .REDIS_HOST }}
    REDIS_PORT: {{ .REDIS_PORT }}
    REDIS_DB: {{ .REDIS_DB }}
{{- end }}