apiVersion: v1
kind: Service
metadata:
  name: python-service
  labels:
    app: python-demo-app
spec:
  type: {{ .Values.Service.type}}
  selector:
    name: python-pod
    app: python-demo-app
  ports:
  - port: {{ .Values.Service.ports.port}}
    targetPort: {{ .Values.Service.ports.targetPort}}
    protocol: {{ .Values.Service.ports.protocol}}
